"""add_contact_inquiries_table

Revision ID: b777cf49b42d
Revises: da0a055046c3
Create Date: 2026-02-02 17:14:48.215613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b777cf49b42d'
down_revision = 'da0a055046c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
